// Code generated by protoc-gen-vkit.
// versions:
// - protoc-gen-vkit v1.0.0

package handler

import (
	context "context"

	"github.com/vison888/logcollector/handler/log"
	pb "github.com/vison888/logcollector/proto/log_collector"
)

type LogService struct {
}

func (the *LogService) One(ctx context.Context, req *pb.CollectOneReq, resp *pb.CollectOneResp) error {
	logObj := &pb.Log{
		Module:    req.Module,
		MeetingId: req.MeetingId,
		UserId:    req.UserId,
		Info:      req.Info,
		Timestamp: req.Timestamp,
	}
	err := log.Log(logObj)
	if err != nil {
		resp.Code = -1
		resp.Msg = err.Error()
	}
	return nil
}

func (the *LogService) Batch(ctx context.Context, req *pb.CollectBatchReq, resp *pb.CollectBatchResp) error {
	err := log.Logs(req.Logs)
	if err != nil {
		resp.Code = -1
		resp.Msg = err.Error()
	}
	return nil
}
